#!/usr/bin/env python
"""Append remaining views to _views_new.py."""
lines = open('_views_new.py', 'r', encoding='utf-8').read().splitlines()
A = lines.append

A('')
A('')
A('def _dec(value):')
A('    try:')
A('        return Decimal(str(value))')
A('    except (InvalidOperation, TypeError, ValueError):')
A('        return None')
A('')
A('')
A('# --- 1. Users ---')
A('@admin_required')
A('def users(request):')
A('    users_list = User.objects.select_related(\'profile\').annotate(')
A('        deposit_total=Sum(\'deposits__amount\', filter=Q(deposits__status=\'approved\')),')
A('    ).order_by(\'-date_joined\')')
A('')
A('    if request.method == \'POST\':')
A('        target = get_object_or_404(User, pk=request.POST.get(\'pk\'))')
A('        action = request.POST.get(\'action\')')
A('        if target != request.user:')
A('            if action == \'toggle_active\':')
A('                target.is_active = not target.is_active')
A('                target.save()')
A('                state = \'Enabled\' if target.is_active else \'Disabled\'')
A('                log_action(request.user, f\'{state} account for {target.username}\')')
A('            elif action == \'toggle_staff\':')
A('                target.is_staff = not target.is_staff')
A('                target.save()')
A('                state = \'Granted\' if target.is_staff else \'Revoked\'')
A('                log_action(request.user, f\'{state} staff access for {target.username}\')')
A('        return redirect(\'adminpanel:users\')')
A('')
A('    return render(request, \'adminpanel/users.html\', {\'users_list\': users_list})')

open('_views_new.py', 'w', encoding='utf-8').write('\n'.join(lines))
print("Users section appended")
