#!/usr/bin/env python
"""Append plans sections to _views_new.py."""
lines = open('_views_new.py', 'r', encoding='utf-8').read().splitlines()
A = lines.append

A('')
A('')
A('# --- 2. Plans ---')
A('@admin_required')
A('def plans(request):')
A('    if request.method == \'POST\':')
A('        action = request.POST.get(\'action\')')
A('        if action == \'import\':')
A('            created = 0')
A('            for order, (name, badge, price, accent) in enumerate(DEFAULT_PLANS):')
A('                _, was_created = Plan.objects.get_or_create(')
A('                    name=name,')
A('                    defaults={\'badge\': badge, \'price\': price, \'accent\': accent,')
A('                              \'daily_percent\': 3, \'duration_days\': 30, \'sort_order\': order},')
A('                )')
A('                created += int(was_created)')
A('            log_action(request.user, f\'Imported default plans ({created} new)\')')
A('        elif action == \'delete\':')
A('            plan = get_object_or_404(Plan, pk=request.POST.get(\'pk\'))')
A('            name = plan.name')
A('            plan.delete()')
A('            log_action(request.user, f\'Deleted plan "{name}"\')')
A('        return redirect(\'adminpanel:plans\')')
A('')
A('    return render(request, \'adminpanel/plans.html\', {')
A('        \'plans_list\': Plan.objects.all(),')
A('    })')
A('')
A('')
A('@admin_required')
A('def plan_form(request, pk=None):')
A('    plan = get_object_or_404(Plan, pk=pk) if pk else None')
A('    error = None')
A('')
A('    if request.method == \'POST\':')
A('        name = request.POST.get(\'name\', \'\').strip()')
A('        price = _dec(request.POST.get(\'price\'))')
A('        percent = _dec(request.POST.get(\'daily_percent\'))')
A('        days = request.POST.get(\'duration_days\')')
A('        if not name or price is None or price <= 0 or percent is None or not days:')
A('            error = \'Fill in a valid name, price, percent and duration.\'')
A('        else:')
A('            if plan is None:')
A('                plan = Plan()')
A('                log_action(request.user, f\'Added new plan "{name}"\')')
A('            else:')
A('                log_action(request.user, f\'Updated plan "{name}"\')')
A('            plan.name = name')
A('            plan.badge = request.POST.get(\'badge\', \'basic\')')
A('            plan.badge_text = request.POST.get(\'badge_text\', \'\').strip()')
A('            plan.badge_gradient_from = request.POST.get(\'badge_gradient_from\', \'#FF6B6B\') or \'#FF6B6B\'')
A('            plan.badge_gradient_to = request.POST.get(\'badge_gradient_to\', \'#F7971E\') or \'#F7971E\'')
A('            plan.accent = request.POST.get(\'accent\') == \'on\'')
A('            plan.daily_percent = percent')
A('            plan.duration_days = int(days)')
A('            plan.price = price')
A('            plan.is_active = request.POST.get(\'is_active\') == \'on\'')
A('            plan.sort_order = int(request.POST.get(\'sort_order\') or 0)')
A('            plan.save()')
A('            return redirect(\'adminpanel:plans\')')
A('')
A('    return render(request, \'adminpanel/plan_form.html\', {')
A('        \'plan\': plan,')
A('        \'error\': error,')
A('        \'badges\': Plan.BADGES,')
A('    })')

open('_views_new.py', 'w', encoding='utf-8').write('\n'.join(lines))
print("Plans sections appended")
