#!/usr/bin/env python
"""Append deposits + withdrawals to _views_new.py."""
lines = open('_views_new.py', 'r', encoding='utf-8').read().splitlines()
A = lines.append

A('')
A('')
A('# --- 3. Deposits ---')
A('@admin_required')
A('def deposits(request):')
A('    if request.method == \'POST\':')
A('        dep = get_object_or_404(Deposit, pk=request.POST.get(\'pk\'))')
A('        action = request.POST.get(\'action\')')
A('        if dep.status == \'pending\' and action in (\'approve\', \'reject\'):')
A('            dep.status = \'approved\' if action == \'approve\' else \'rejected\'')
A('            dep.save()')
A('            dep.transactions.update(status=dep.status)')
A('            if dep.status == \'approved\':')
A('                from dashboard.services import credit_wallet, send_email')
A('                credit_wallet(dep)')
A('                send_email(')
A('                    dep.user.email,')
A('                    \'Deposit Approved\',')
A("                    f'<p>Your deposit of <strong>\u20a6{dep.amount:,.2f}</strong> has been approved and credited to your wallet.</p>',")
A('                    name=dep.user.get_full_name() or dep.user.username,')
A('                )')
A('            elif dep.status == \'rejected\':')
A('                from dashboard.services import send_email')
A('                send_email(')
A('                    dep.user.email,')
A('                    \'Deposit Rejected\',')
A("                    f'<p>Your deposit of <strong>\u20a6{dep.amount:,.2f}</strong> has been rejected.</p>',")
A('                    name=dep.user.get_full_name() or dep.user.username,')
A('                )')
A("            log_action(request.user, f'{dep.status.title()} deposit #{dep.id} '")
A("                       f'(\u20a6{dep.amount:,.0f}) by {dep.user.username}')")
A('        return redirect(\'adminpanel:deposits\')')
A('')
A('    return render(request, \'adminpanel/deposits.html\', {')
A('        \'deposits_list\': Deposit.objects.select_related(\'user\', \'plan\'),')
A('    })')
A('')
A('')
A('# --- 4. Withdrawals ---')
A('@admin_required')
A('def withdrawals(request):')
A('    from dashboard.services import mark_withdrawal_paid')
A('    if request.method == \'POST\':')
A('        wd = get_object_or_404(Withdrawal, pk=request.POST.get(\'pk\'))')
A('        action = request.POST.get(\'action\')')
A('        if wd.status == \'pending\' and action in (\'approve\', \'reject\'):')
A('            wd.status = \'approved\' if action == \'approve\' else \'rejected\'')
A('            wd.save()')
A('            wd.transactions.update(status=wd.status)')
A('            if wd.status == \'approved\':')
A('                wd.paid = True')
A('                wd.reviewed_at = timezone.now()')
A("                wd.save(update_fields=['paid', 'reviewed_at'])")
A("                log_action(request.user, f'{wd.status.title()} withdrawal #{wd.id} '")
A("                       f'(\u20a6{wd.amount:,.0f}) by {wd.user.username}')")
A('                wd.delete()')
A('            else:')
A("                log_action(request.user, f'{wd.status.title()} withdrawal #{wd.id} '")
A("                       f'(\u20a6{wd.amount:,.0f}) by {wd.user.username}')")
A('        elif action == \'paid\' and not wd.paid:')
A('            mark_withdrawal_paid(wd)')
A('            wd.delete()')
A('        return redirect(\'adminpanel:withdrawals\')')
A('')
A('    return render(request, \'adminpanel/withdrawals.html\', {')
"A('        \'withdrawals_list\': Withdrawal.objects.select_related(\'user\').filter(paid=False),')")
A('    })')

open('_views_new.py', 'w', encoding='utf-8').write('\n'.join(lines))
print("Deposits + Withdrawals appended")
