# Generated by Django 6.1.1 on 2026-09-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='usdt_bep20_address',
            field=models.CharField(blank=True, default='', help_text='Platform BEP20 (BSC) USDT deposit address. Users send crypto here.', max_length=255),
        ),
    ]
