# Generated by Django 6.1.1 on 2026-09-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_transaction_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='admin_confirmed',
            field=models.BooleanField(default=False, help_text='Set True manually if you credit the wallet by hand (dev fallback).'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='paystack_ref',
            field=models.CharField(blank=True, help_text='Paystack transaction reference (for verification).', max_length=191),
        ),
        migrations.AddField(
            model_name='deposit',
            name='verified',
            field=models.BooleanField(default=False, help_text='Set True after Paystack callback verifies the payment.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Mark True after emailing the notification to all users.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='badge_gradient_from',
            field=models.CharField(default='#FF6B6B', help_text='Hex color for the badge gradient start, e.g. #FF6B6B', max_length=7),
        ),
        migrations.AddField(
            model_name='plan',
            name='badge_gradient_to',
            field=models.CharField(default='#F7971E', help_text='Hex color for the badge gradient end, e.g. #F7971E', max_length=7),
        ),
        migrations.AddField(
            model_name='plan',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Custom badge label, e.g. "Best Value". Leave blank to use the default badge.', max_length=40),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='requested_at',
            field=models.DateTimeField(blank=True, help_text='When the user submitted the request (for once-per-day limit).', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('referral', 'Referral Credit')], max_length=12),
        ),
    ]
