# Generated by Django 6.1.1 on 2026-09-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_notificationdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='usdt_tx_hash',
            field=models.CharField(blank=True, default='', help_text='Blockchain transaction hash submitted by user for USDT deposits.', max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='usdt_network',
            field=models.CharField(blank=True, choices=[('bep20', 'BEP20 (BSC)'), ('trc20', 'TRC20 (TRON)')], default='bep20', help_text='The blockchain network the user wants payout on.', max_length=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('usdt', 'USDT BEP20')], default='bank', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('usdt', 'USDT BEP20')], default='bank', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='usdt_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
