# Generated by Django 6.1.1 on 2026-09-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_referral_balance_profile_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_email',
            field=models.BooleanField(default=True, help_text='Email notifications for deposits/withdrawals.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_referral',
            field=models.BooleanField(default=True, help_text='Referral commission alerts.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_roi',
            field=models.BooleanField(default=True, help_text='Daily ROI credit alerts.'),
        ),
    ]
